# docker-compose.yml
version: "3.9"

services:
  db:
    image: postgres:15
    container_name: atmgo-postgres
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./app/static/data/init.sql:/docker-entrypoint-initdb.d/init.sql

  web:
    build: .
    container_name: atmgo-api
    env_file: .env
    volumes:
      - .:/app
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  pgdata:
